### ISSUE TITLE
Question about blocking of www.lyrical-nonsense.com

### ISSUE THREAD

**Issue by NDavies-02** [mullvad/dns-blocklists#112] opened 2023-10-03 18:36 UTC
Currently using Mullvad DNS using Windows 11 encrypted DNS and also on Android via Private DNS.

I notice that the site `www.lyrical-nonsense.com` does not resolve when using it. (`ERR_NAME_NOT_RESOLVED` error on Windows/Edge; DNS cannot be resolved error on Android browser)

This is even true for the non-blocking `dns.mullvad.net`, though I generally use `base.dns.mullvad.net`.

I am able to access the website again upon switching to any other non-Mullvad DNS provider.

Is this an issue, or a deliberate decision? Apologies if this is not the correct way to report this issue.

**Comment by oskaralmlov** [comment] 2023-10-04 07:13
Unfortunately I'm unable to reproduce your issue (under Linux, I don't have a window machine). 

However I can say this; the only domains that our service blocks are those that are listed in the below repository and only when the user chooses to enable the specific "blocking categories":
https://github.com/mullvad/dns-blocklists

9/10 times when something like this happens it's because the dns servers that are authoritative (responsible) for that domain are blocking our servers from resolving that domain. It's an unfortunate side-effect of our servers IP addresses being public - some people block them. 

An FYI here is that our encrypted dns service is anycasted. Meaning that multiple servers are configured with the same IP and your traffic will be routed to the one that is closest to you. So if that closest server ends up being blocked from resolving $DOMAIN the other servers might still be able to resolve it. Whenever this happens you could try and switch to using a specific server directly rather than `dns.mullvad.net`(note that configuring these hostnames as your resolver is equivalent of `dns.mullvad.net` and that there is no adblocking/base/extended versions) :
```
de-fra-dns-001.mullvad.net
gb-lon-dns-001.mullvad.net
gb-lon-dns-301.mullvad.net
se-got-dns-001.mullvad.net
se-mma-dns-001.mullvad.net
se-sto-dns-001.mullvad.net
sg-sin-dns-101.mullvad.net
us-lax-dns-401.mullvad.net
us-nyc-dns-601.mullvad.net
```

**Closed as completed** 2023-10-07 19:24 UTC
